WITH T as (
    SELECT 
        MAX(PRICE) as MAX_PRICE
    FROM 
        FOOD_PRODUCT
)
SELECT
    PRODUCT_ID
    , PRODUCT_NAME
    , PRODUCT_CD
    , CATEGORY
    , PRICE
FROM 
    FOOD_PRODUCT, T
WHERE
    PRICE = MAX_PRICE